export const types = {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_ITEM: 'REMOVE_ITEM',
    SUB_QUANTITY: 'SUB_QUANTITY',
    ADD_QUANTITY: 'ADD_QUANTITY',
    CLEAN_CART: 'CLEAN_CART',
    TOGGLE_WISH_LIST: 'TOGGLE_WISH_LIST', 
};